theme: jekyll-theme-slate
title: Welcome to Bryson's Portfolio!
description: I periodically update this website with new projects that I've been working on. Feel free to check in to see what I've been up to!
![Headshot of Bryson](/images/headshot.jpg "Headshot of Bryson")
